### ISSUE TITLE
Dataset link

### ISSUE THREAD

**Issue by andrea-garritano** [salmank255/deepsmoke#1]
Hi @salmank255,
i've read your paper about DeepSmoke, but the dataset seem to be missing.
Could you provide me a link where i can download it?

Thanks,
Andrea Garritano

**Comment by hamddan4** [comment]
Yep, the link seems to be missing...

**Comment by salmank255** [comment]
The dataset is added to the repo, please check it out. 

Note: the dataset is not in the original format (images from other smoke segmentation repo are added).
